### ISSUE TITLE
Building on macOS Sierra

### ISSUE THREAD

**Issue by bitjson** [bitcoin-hivemind/hivemind#82]
No trouble building on Debian, but I'm getting the below while trying to build on macOS Sierra `10.12 Beta (16A294a)`:

```
:hivemind jason$ make
Making all in src
  CXXLD    libhivemindconsensus.la
Undefined symbols for architecture x86_64:
  "eccrypto::CheckSignatureElement(unsigned char const*, int, bool)", referenced from:
      CheckSignatureEncoding(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, unsigned int, ScriptError_t*) in libhivemindconsensus_la-interpreter.o
  "CECKey::Verify(uint256 const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&)", referenced from:
      CPubKey::Verify(uint256 const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) const in libhivemindconsensus_la-pubkey.o
  "CECKey::CECKey()", referenced from:
      CPubKey::Verify(uint256 const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) const in libhivemindconsensus_la-pubkey.o
  "CECKey::SetPubKey(unsigned char const*, unsigned long)", referenced from:
      CPubKey::Verify(uint256 const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) const in libhivemindconsensus_la-pubkey.o
  "CECKey::~CECKey()", referenced from:
      CPubKey::Verify(uint256 const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) const in libhivemindconsensus_la-pubkey.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libhivemindconsensus.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

Any ideas?

**Comment by bitjson** [comment]
Got it building – was not an issue with the project. (I basically removed all the dependencies, and went through [these steps](https://github.com/bitcoin-hivemind/hivemind/blob/master/doc/build-osx.md) again.)

For anyone finding this in the future, be sure to check the [`bitcoin/bitcoin` macOS instructions](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md) for hints too.

**Comment by bitjson** [comment]
One additional thing to try – I have the `CPPFLAGS` environment variable set in my `~/.bash_profile` to:

``` bash
export CPPFLAGS="-I/usr/local/opt/openssl/include -I/usr/local/opt/qt5/include"
```

Which solved an issue I had before when trying to build with software versions installed by brew.
